export interface WallSettingsModel{readonly version:1;readonly externalWallThicknessMm:number;}
interface PersistedWallSettingsCollection{readonly version:2;readonly byStoreyId:Record<string,WallSettingsModel>;}
export const WALL_SETTINGS_CHANGED_EVENT='smartbarn:wall-settings-changed';
const LEGACY_STORAGE_KEY='smartbarn.wall-settings.v1',STORAGE_KEY='smartbarn.wall-settings.v2',DEFAULT_STOREY_ID='storey-1';
export const DEFAULT_WALL_SETTINGS:WallSettingsModel={version:1,externalWallThicknessMm:174};
function clamp(value:unknown,fallback:number){const n=Number(value);return Number.isFinite(n)?Math.min(1000,Math.max(50,Math.round(n))):fallback;}
function normalize(value:unknown):WallSettingsModel{const parsed=(value&&typeof value==='object'?value:{}) as Partial<WallSettingsModel>;return{version:1,externalWallThicknessMm:clamp(parsed.externalWallThicknessMm,174)};}
function readCollection():PersistedWallSettingsCollection{if(typeof window==='undefined')return{version:2,byStoreyId:{[DEFAULT_STOREY_ID]:DEFAULT_WALL_SETTINGS}};try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const parsed=JSON.parse(raw) as Partial<PersistedWallSettingsCollection>;const byStoreyId:Record<string,WallSettingsModel>={};if(parsed.byStoreyId&&typeof parsed.byStoreyId==='object')for(const[id,value]of Object.entries(parsed.byStoreyId))byStoreyId[id]=normalize(value);return{version:2,byStoreyId};}const legacyRaw=localStorage.getItem(LEGACY_STORAGE_KEY);const legacy=legacyRaw?normalize(JSON.parse(legacyRaw)):DEFAULT_WALL_SETTINGS;const migrated={version:2 as const,byStoreyId:{[DEFAULT_STOREY_ID]:legacy}};localStorage.setItem(STORAGE_KEY,JSON.stringify(migrated));return migrated;}catch{return{version:2,byStoreyId:{[DEFAULT_STOREY_ID]:DEFAULT_WALL_SETTINGS}};}}
export function loadWallSettings(storeyId=DEFAULT_STOREY_ID):WallSettingsModel{const collection=readCollection();return normalize(collection.byStoreyId[storeyId]??collection.byStoreyId[DEFAULT_STOREY_ID]??DEFAULT_WALL_SETTINGS);}
export function saveWallSettings(settings:WallSettingsModel,storeyId=DEFAULT_STOREY_ID):void{if(typeof window==='undefined')return;const collection=readCollection();collection.byStoreyId[storeyId]=normalize(settings);localStorage.setItem(STORAGE_KEY,JSON.stringify(collection));window.dispatchEvent(new CustomEvent(WALL_SETTINGS_CHANGED_EVENT,{detail:{storeyId}}));}
export function cloneWallSettingsForStorey(sourceStoreyId:string,targetStoreyId:string):void{saveWallSettings(loadWallSettings(sourceStoreyId),targetStoreyId);}
export function removeWallSettingsForStorey(storeyId:string):void{if(typeof window==='undefined')return;const collection=readCollection();delete collection.byStoreyId[storeyId];localStorage.setItem(STORAGE_KEY,JSON.stringify(collection));window.dispatchEvent(new CustomEvent(WALL_SETTINGS_CHANGED_EVENT,{detail:{storeyId}}));}
