import { materialById } from '../materials/material-catalog';
export type WallLayerZone='exterior'|'core'|'interior';
export interface WallLayer{readonly id:number;readonly materialId:string;readonly thicknessMm:number;readonly zone:WallLayerZone;}
export interface WallSettingsModel{readonly version:3;readonly sideWallHeightMm:number;readonly roofPitchDeg:number;readonly layers:readonly WallLayer[];}
interface PersistedWallSettingsCollection{readonly version:4;readonly byStoreyId:Record<string,WallSettingsModel>;}
export const WALL_SETTINGS_CHANGED_EVENT='smartbarn:wall-settings-changed';
const OLD_KEY='smartbarn.wall-settings.v3',STORAGE_KEY='smartbarn.wall-settings.v4',DEFAULT_STOREY_ID='storey-1';
const DEFAULT_LAYERS:readonly WallLayer[]=[{id:1,materialId:'osb-3',thicknessMm:12,zone:'core'},{id:2,materialId:'eps',thicknessMm:150,zone:'core'},{id:3,materialId:'osb-3',thicknessMm:12,zone:'core'}];
export const DEFAULT_WALL_SETTINGS:WallSettingsModel={version:3,sideWallHeightMm:2500,roofPitchDeg:30,layers:DEFAULT_LAYERS};
function clamp(v:unknown,f:number,min:number,max:number){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,Math.round(n))):f;}
function zone(v:unknown):WallLayerZone{return v==='exterior'||v==='interior'||v==='core'?v:'core';}
function normalizeLayer(v:unknown,i:number):WallLayer|undefined{if(!v||typeof v!=='object')return;const l=v as Partial<WallLayer>;const materialId=typeof l.materialId==='string'&&materialById(l.materialId)?l.materialId:'osb-3';return{id:clamp(l.id,i+1,1,Number.MAX_SAFE_INTEGER),materialId,thicknessMm:clamp(l.thicknessMm,materialById(materialId)?.defaultThicknessMm??12,1,2000),zone:zone(l.zone)};}
function clone(m:WallSettingsModel):WallSettingsModel{return{version:3,sideWallHeightMm:m.sideWallHeightMm,roofPitchDeg:m.roofPitchDeg,layers:m.layers.map(l=>({...l}))};}
function normalize(v:unknown):WallSettingsModel{const p=(v&&typeof v==='object'?v:{}) as Partial<WallSettingsModel>;const layers=Array.isArray(p.layers)?p.layers.map(normalizeLayer).filter((x):x is WallLayer=>!!x):DEFAULT_LAYERS.map(x=>({...x}));return{version:3,sideWallHeightMm:clamp(p.sideWallHeightMm,2500,1000,6000),roofPitchDeg:clamp(p.roofPitchDeg,30,5,80),layers:layers.length?layers:DEFAULT_LAYERS.map(x=>({...x}))};}
function readCollection():PersistedWallSettingsCollection{if(typeof window==='undefined')return{version:4,byStoreyId:{[DEFAULT_STOREY_ID]:clone(DEFAULT_WALL_SETTINGS)}};try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const p=JSON.parse(raw) as Partial<PersistedWallSettingsCollection>,byStoreyId:Record<string,WallSettingsModel>={};if(p.byStoreyId)for(const[id,v]of Object.entries(p.byStoreyId))byStoreyId[id]=normalize(v);return{version:4,byStoreyId};}const old=localStorage.getItem(OLD_KEY);if(old){const p=JSON.parse(old) as {byStoreyId?:Record<string,unknown>},byStoreyId:Record<string,WallSettingsModel>={};if(p.byStoreyId)for(const[id,v]of Object.entries(p.byStoreyId))byStoreyId[id]=normalize(v);const m={version:4 as const,byStoreyId};localStorage.setItem(STORAGE_KEY,JSON.stringify(m));return m;}}catch{}return{version:4,byStoreyId:{[DEFAULT_STOREY_ID]:clone(DEFAULT_WALL_SETTINGS)}};}
export function loadWallSettings(id=DEFAULT_STOREY_ID){return clone(readCollection().byStoreyId[id]??DEFAULT_WALL_SETTINGS);}
export function saveWallSettings(s:WallSettingsModel,id=DEFAULT_STOREY_ID){if(typeof window==='undefined')return;const c=readCollection();c.byStoreyId[id]=clone(normalize(s));localStorage.setItem(STORAGE_KEY,JSON.stringify(c));window.dispatchEvent(new CustomEvent(WALL_SETTINGS_CHANGED_EVENT,{detail:{storeyId:id}}));}
export function cloneWallSettingsForStorey(source:string,target:string){if(typeof window==='undefined')return;const c=readCollection();c.byStoreyId[target]=clone(c.byStoreyId[source]??DEFAULT_WALL_SETTINGS);localStorage.setItem(STORAGE_KEY,JSON.stringify(c));window.dispatchEvent(new CustomEvent(WALL_SETTINGS_CHANGED_EVENT,{detail:{storeyId:target}}));}
export function removeWallSettingsForStorey(id:string){if(typeof window==='undefined')return;const c=readCollection();delete c.byStoreyId[id];localStorage.setItem(STORAGE_KEY,JSON.stringify(c));window.dispatchEvent(new CustomEvent(WALL_SETTINGS_CHANGED_EVENT,{detail:{storeyId:id}}));}
export function wallThicknessMm(s:WallSettingsModel){return s.layers.reduce((sum,l)=>sum+l.thicknessMm,0);}
export function wallZoneThicknessMm(s:WallSettingsModel,z:WallLayerZone){return s.layers.filter(l=>l.zone===z).reduce((sum,l)=>sum+l.thicknessMm,0);}
