import { computed } from '@angular/core';
import { patchState, signalStore, withComputed, withMethods, withState } from '@ngrx/signals';
import { materialById } from '../materials/material-catalog';

export const FLOOR_FIELD_CHANGED_EVENT='smartbarn:floor-field-changed';
export type FloorLayerWallPlacement='under-walls'|'between-walls';
export interface FloorLayer { readonly id:number; readonly materialId:string; readonly kind:string; readonly name:string; readonly thicknessMm:number; readonly color:string; readonly wallPlacement:FloorLayerWallPlacement; }
export interface FloorFieldModel{readonly version:1;readonly lengthMm:number;readonly widthMm:number;readonly elevationMm:number;readonly layers:readonly FloorLayer[];}
type FloorFieldStoreStatus='idle'|'ready'|'error';
interface FloorFieldState{readonly activeStoreyId:string;readonly lengthMm:number;readonly widthMm:number;readonly elevationMm:number;readonly layers:readonly FloorLayer[];readonly status:FloorFieldStoreStatus;}
interface PersistedFloorFieldCollection{readonly version:2;readonly byStoreyId:Record<string,FloorFieldModel>;}
const LEGACY_STORAGE_KEY='smartbarn.floor-field.v1',STORAGE_KEY='smartbarn.floor-fields.v2',MIN_SIZE_MM=500,MAX_SIZE_MM=50000,DEFAULT_STOREY_ID='storey-1';
const DEFAULT_LAYERS:readonly FloorLayer[]=[
{id:1,materialId:'osb-3',kind:'sheet',name:'OSB-3',thicknessMm:12,color:'#f5d77a',wallPlacement:'under-walls'},
{id:2,materialId:'structural-timber',kind:'wood',name:'Конструкционная древесина',thicknessMm:200,color:'#e58b2a',wallPlacement:'under-walls'},
{id:3,materialId:'osb-3',kind:'sheet',name:'OSB-3',thicknessMm:12,color:'#f5d77a',wallPlacement:'under-walls'}];
const DEFAULT_MODEL:FloorFieldModel={version:1,lengthMm:9000,widthMm:6000,elevationMm:0,layers:DEFAULT_LAYERS};
const initialState:FloorFieldState={activeStoreyId:DEFAULT_STOREY_ID,...DEFAULT_MODEL,status:'idle'};
function clampInteger(value:unknown,fallback:number,min:number,max:number){const n=Number(value);return Number.isFinite(n)?Math.min(max,Math.max(min,Math.round(n))):fallback;}
function inferMaterialId(layer:Partial<FloorLayer>):string{if(typeof layer.materialId==='string'&&materialById(layer.materialId))return layer.materialId;const name=(layer.name??'').toLowerCase();if(name.includes('osb'))return'osb-3';if(name.includes('балк')||name.includes('брус')||name.includes('древес'))return'structural-timber';if(name.includes('ват')||name.includes('теплоизоля'))return'mineral-wool';if(name.includes('стяж'))return'cement-screed';return'osb-3';}
function normalizeWallPlacement(value:unknown):FloorLayerWallPlacement{return value==='between-walls'?'between-walls':'under-walls';}
function normalizeLayer(value:unknown):FloorLayer|undefined{if(!value||typeof value!=='object')return;const layer=value as Partial<FloorLayer>,id=clampInteger(layer.id,0,1,Number.MAX_SAFE_INTEGER);if(!id)return;const materialId=inferMaterialId(layer),material=materialById(materialId);return{id,materialId,kind:material?.group??'other',name:material?.name??'Материал',thicknessMm:clampInteger(layer.thicknessMm,material?.defaultThicknessMm??20,1,2000),color:material?.color??'#8ab4f8',wallPlacement:normalizeWallPlacement(layer.wallPlacement)};}
function normalizePlacementBoundary(layers:readonly FloorLayer[]):FloorLayer[]{const firstUnder=layers.findIndex(l=>l.wallPlacement==='under-walls');if(firstUnder<0)return layers.map(l=>({...l,wallPlacement:'between-walls'}));return layers.map((l,index)=>({...l,wallPlacement:index<firstUnder?'between-walls':'under-walls'}));}
function normalizeModel(value:unknown):FloorFieldModel{if(!value||typeof value!=='object')return cloneModel(DEFAULT_MODEL);const parsed=value as Partial<FloorFieldModel>;const normalized=Array.isArray(parsed.layers)?parsed.layers.map(normalizeLayer).filter((x):x is FloorLayer=>!!x):[...DEFAULT_LAYERS];const layers=normalizePlacementBoundary(normalized);return{version:1,lengthMm:clampInteger(parsed.lengthMm,9000,MIN_SIZE_MM,MAX_SIZE_MM),widthMm:clampInteger(parsed.widthMm,6000,MIN_SIZE_MM,MAX_SIZE_MM),elevationMm:clampInteger(parsed.elevationMm,0,-10000,50000),layers:layers.length?layers:[...DEFAULT_LAYERS]};}
function cloneModel(model:FloorFieldModel):FloorFieldModel{return{...model,layers:model.layers.map(layer=>({...layer}))};}
function readCollection():PersistedFloorFieldCollection{if(typeof window==='undefined')return{version:2,byStoreyId:{[DEFAULT_STOREY_ID]:cloneModel(DEFAULT_MODEL)}};try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const parsed=JSON.parse(raw) as Partial<PersistedFloorFieldCollection>;const byStoreyId:Record<string,FloorFieldModel>={};if(parsed.byStoreyId&&typeof parsed.byStoreyId==='object')for(const[id,value]of Object.entries(parsed.byStoreyId))byStoreyId[id]=normalizeModel(value);return{version:2,byStoreyId};}const legacyRaw=localStorage.getItem(LEGACY_STORAGE_KEY);const legacy=legacyRaw?normalizeModel(JSON.parse(legacyRaw)):cloneModel(DEFAULT_MODEL);const migrated={version:2 as const,byStoreyId:{[DEFAULT_STOREY_ID]:legacy}};localStorage.setItem(STORAGE_KEY,JSON.stringify(migrated));return migrated;}catch{return{version:2,byStoreyId:{[DEFAULT_STOREY_ID]:cloneModel(DEFAULT_MODEL)}};}}
function writeStoreyModel(storeyId:string,model:FloorFieldModel):void{if(typeof window==='undefined')return;const collection=readCollection();collection.byStoreyId[storeyId]=normalizeModel(model);localStorage.setItem(STORAGE_KEY,JSON.stringify(collection));window.dispatchEvent(new CustomEvent(FLOOR_FIELD_CHANGED_EVENT,{detail:{storeyId}}));}
export function loadFloorField(storeyId=DEFAULT_STOREY_ID):FloorFieldModel{const collection=readCollection();return cloneModel(collection.byStoreyId[storeyId]??collection.byStoreyId[DEFAULT_STOREY_ID]??DEFAULT_MODEL);}
export function cloneFloorFieldForStorey(sourceStoreyId:string,targetStoreyId:string):void{writeStoreyModel(targetStoreyId,cloneModel(loadFloorField(sourceStoreyId)));}
export function removeFloorFieldForStorey(storeyId:string):void{if(typeof window==='undefined')return;const collection=readCollection();delete collection.byStoreyId[storeyId];localStorage.setItem(STORAGE_KEY,JSON.stringify(collection));window.dispatchEvent(new CustomEvent(FLOOR_FIELD_CHANGED_EVENT,{detail:{storeyId}}));}
export function loadUnderWallsThicknessMm(storeyId=DEFAULT_STOREY_ID):number{return loadFloorField(storeyId).layers.filter(l=>l.wallPlacement==='under-walls').reduce((sum,l)=>sum+l.thicknessMm,0);}
export const FloorFieldStore=signalStore({providedIn:'root'},withState(initialState),withComputed(({layers})=>({totalLayerThicknessMm:computed(()=>layers().reduce((s,l)=>s+l.thicknessMm,0)),underWallsThicknessMm:computed(()=>layers().filter(l=>l.wallPlacement==='under-walls').reduce((s,l)=>s+l.thicknessMm,0)),betweenWallsThicknessMm:computed(()=>layers().filter(l=>l.wallPlacement==='between-walls').reduce((s,l)=>s+l.thicknessMm,0))})),withMethods(store=>{const currentModel=():FloorFieldModel=>({version:1,lengthMm:store.lengthMm(),widthMm:store.widthMm(),elevationMm:store.elevationMm(),layers:store.layers()});const persist=()=>writeStoreyModel(store.activeStoreyId(),currentModel());const update=(state:Partial<FloorFieldState>)=>{patchState(store,state);persist();};const activate=(storeyId:string)=>{const model=loadFloorField(storeyId);patchState(store,{activeStoreyId:storeyId,...model,status:'ready'});};return{
initialize(storeyId=DEFAULT_STOREY_ID){if(store.status()==='idle')activate(storeyId);else if(store.activeStoreyId()!==storeyId)activate(storeyId);},switchStorey(storeyId:string){if(store.activeStoreyId()!==storeyId)activate(storeyId);},setLength(v:number){update({lengthMm:clampInteger(v,store.lengthMm(),MIN_SIZE_MM,MAX_SIZE_MM)});},setWidth(v:number){update({widthMm:clampInteger(v,store.widthMm(),MIN_SIZE_MM,MAX_SIZE_MM)});},setElevation(v:number){update({elevationMm:clampInteger(v,store.elevationMm(),-10000,50000)});},swapDimensions(){update({lengthMm:store.widthMm(),widthMm:store.lengthMm()});},resetGeometry(){update({lengthMm:9000,widthMm:6000,elevationMm:0});},
addLayer(position:'top'|'bottom'){const nextId=Math.max(0,...store.layers().map(l=>l.id))+1,m=materialById('osb-3')!;const current=store.layers(),wallPlacement:FloorLayerWallPlacement=position==='top'&&current.some(l=>l.wallPlacement==='between-walls')?'between-walls':'under-walls';const layer:FloorLayer={id:nextId,materialId:m.id,kind:m.group,name:m.name,thicknessMm:m.defaultThicknessMm??20,color:m.color,wallPlacement};update({layers:normalizePlacementBoundary(position==='top'?[layer,...current]:[...current,layer])});},removeLayer(id:number){update({layers:normalizePlacementBoundary(store.layers().filter(l=>l.id!==id))});},
setLayerMaterial(id:number,materialId:string){const m=materialById(materialId);if(!m)return;update({layers:store.layers().map(l=>l.id===id?{...l,materialId:m.id,kind:m.group,name:m.name,thicknessMm:m.defaultThicknessMm??l.thicknessMm,color:m.color}:l)});},
updateLayer(id:number,patch:Partial<Pick<FloorLayer,'color'|'thicknessMm'|'wallPlacement'>>){const layers=store.layers().map(l=>l.id===id?{...l,...patch,wallPlacement:patch.wallPlacement===undefined?l.wallPlacement:normalizeWallPlacement(patch.wallPlacement),thicknessMm:patch.thicknessMm===undefined?l.thicknessMm:clampInteger(patch.thicknessMm,l.thicknessMm,1,2000)}:l);if(patch.wallPlacement!==undefined){const index=layers.findIndex(l=>l.id===id);const placement=normalizeWallPlacement(patch.wallPlacement);update({layers:layers.map((l,i)=>({...l,wallPlacement:placement==='between-walls'?(i<=index?'between-walls':l.wallPlacement):(i>=index?'under-walls':l.wallPlacement)}))});return;}update({layers});},
reorderLayers(sourceId:number,targetId:number,position:'before'|'after'){if(sourceId===targetId)return;const layers=[...store.layers()];const si=layers.findIndex(l=>l.id===sourceId);let ti=layers.findIndex(l=>l.id===targetId);if(si<0||ti<0)return;const[m]=layers.splice(si,1);if(si<ti)ti--;layers.splice(position==='after'?ti+1:ti,0,m);update({layers:normalizePlacementBoundary(layers)});}
};}));
