import { ChangeDetectionStrategy, Component, OnDestroy, computed, inject, signal } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { TranslocoPipe } from '@jsverse/transloco';
import { Subscription } from 'rxjs';
import { lucidePanelRight, lucidePlus, lucideX } from '@smartbarn/icons';
import { IconComponent, provideIcons } from '@smartbarn/ui-kit';
import { BUILDING_STRUCTURE_CHANGED_EVENT, loadBuildingStructure, type BuildingStructureModel } from '../building-structure/building-structure';
import { loadWallSettings, WALL_SETTINGS_CHANGED_EVENT } from '../walls/wall-settings';
import { FloorField3dComponent } from './floor-field-3d.component';
import { FloorFieldPreferencesStore,type CameraModePreference,type FloorFieldViewPreference } from './floor-field-preferences.store';
import { FloorFieldStore,type FloorLayerWallPlacement } from './floor-field.store';
import { MaterialComboboxComponent } from './material-combobox.component';
import { loadMaterialCatalog } from '../materials/material-catalog';
type ResizeHandle='length'|'width'|'both';interface PreviewRect{readonly x:number;readonly y:number;readonly width:number;readonly height:number;}
@Component({selector:'smartbarn-floor-field-page',standalone:true,imports:[FloorField3dComponent,MaterialComboboxComponent,TranslocoPipe,IconComponent],providers:[...provideIcons(lucidePanelRight,lucidePlus,lucideX)],changeDetection:ChangeDetectionStrategy.OnPush,templateUrl:'./floor-field.page.html',styleUrl:'./floor-field.page.scss'})
export class FloorFieldPage implements OnDestroy{
 private static readonly MIN=500;private static readonly MAX=50000;private draggedLayerId:number|null=null;private dragResizeState:{handle:ResizeHandle;startX:number;startY:number;startLength:number;startWidth:number}|null=null;
 private readonly store=inject(FloorFieldStore);private readonly preferences=inject(FloorFieldPreferencesStore);private readonly route=inject(ActivatedRoute);private readonly routeSub:Subscription;readonly activeStoreyId=signal('storey-1');readonly materials=loadMaterialCatalog();readonly buildingStructure=signal<BuildingStructureModel>(loadBuildingStructure());readonly externalWallThicknessMm=signal(174);
 readonly linkedStorey=computed(()=>this.buildingStructure().storeys.find(item=>item.id===this.activeStoreyId())??null);readonly elevationLinked=computed(()=>!!this.linkedStorey());
 readonly lengthMm=this.store.lengthMm;readonly widthMm=this.store.widthMm;readonly elevationMm=this.store.elevationMm;readonly layers=this.store.layers;readonly totalLayerThicknessMm=this.store.totalLayerThicknessMm;readonly underWallsThicknessMm=this.store.underWallsThicknessMm;readonly wallSectionInsetPx=computed(()=>Math.min(56,Math.max(8,this.externalWallThicknessMm()*.15)));readonly gridStepMm=this.preferences.gridStepMm;readonly snapToGrid=this.preferences.snapToGrid;readonly activeView=this.preferences.activeView;readonly inspectorOpen=this.preferences.inspectorOpen;readonly show3dGrid=this.preferences.show3dGrid;readonly navigationMode=this.preferences.navigationMode;readonly cameraMode=this.preferences.cameraMode;readonly camera=this.preferences.camera;readonly hiddenLayerIds=this.preferences.hiddenLayerIds;readonly dragOverLayerId=signal<number|null>(null);readonly dragOverPosition=signal<'before'|'after'|null>(null);
 readonly previewRect=computed<PreviewRect>(()=>{const aw=760,ah=500,a=this.lengthMm()/this.widthMm(),aa=aw/ah,w=a>=aa?aw:ah*a,h=a>=aa?aw/a:ah;return{x:(1000-w)/2,y:(650-h)/2,width:w,height:h};});
 private readonly refreshBuildingStructure=()=>{this.buildingStructure.set(loadBuildingStructure());this.syncLinkedElevation();};private readonly refreshWallSettings=()=>this.externalWallThicknessMm.set(loadWallSettings(this.activeStoreyId()).externalWallThicknessMm);
 constructor(){this.preferences.initialize();this.routeSub=this.route.queryParamMap.subscribe(params=>{const storeyId=params.get('storey')??'storey-1';this.activeStoreyId.set(storeyId);this.store.initialize(storeyId);this.store.switchStorey(storeyId);this.externalWallThicknessMm.set(loadWallSettings(storeyId).externalWallThicknessMm);this.buildingStructure.set(loadBuildingStructure());this.syncLinkedElevation();});if(typeof window!=='undefined'){window.addEventListener(BUILDING_STRUCTURE_CHANGED_EVENT,this.refreshBuildingStructure);window.addEventListener(WALL_SETTINGS_CHANGED_EVENT,this.refreshWallSettings);}}
 ngOnDestroy():void{this.routeSub.unsubscribe();if(typeof window!=='undefined'){window.removeEventListener(BUILDING_STRUCTURE_CHANGED_EVENT,this.refreshBuildingStructure);window.removeEventListener(WALL_SETTINGS_CHANGED_EVENT,this.refreshWallSettings);}}
 setActiveView(v:FloorFieldViewPreference){this.preferences.setActiveView(v);}toggleInspector(){this.preferences.setInspectorOpen(!this.inspectorOpen());}toggleSnapToGrid(){this.preferences.setSnapToGrid(!this.snapToGrid());}toggle3dGrid(){this.preferences.setShow3dGrid(!this.show3dGrid());}
 updateLength(e:Event){this.store.setLength(this.snap(this.read(e,this.lengthMm(),500,50000)));}updateWidth(e:Event){this.store.setWidth(this.snap(this.read(e,this.widthMm(),500,50000)));}updateElevation(e:Event){if(this.elevationLinked())return;this.store.setElevation(this.read(e,this.elevationMm(),-10000,50000));}updateGridStep(e:Event){this.preferences.setGridStepMm(this.read(e,this.gridStepMm(),10,5000));}swapDimensions(){this.store.swapDimensions();}resetGeometry(){this.store.resetGeometry();this.syncLinkedElevation();this.preferences.setGridStepMm(100);this.preferences.setSnapToGrid(true);}resetWorkspace(){this.preferences.resetWorkspace();}
 startResize(handle:ResizeHandle,e:PointerEvent){e.preventDefault();(e.currentTarget as Element).setPointerCapture?.(e.pointerId);this.dragResizeState={handle,startX:e.clientX,startY:e.clientY,startLength:this.lengthMm(),startWidth:this.widthMm()};}resizeGeometry(e:PointerEvent){const s=this.dragResizeState;if(!s)return;const r=this.previewRect(),pxL=r.width/s.startLength,pxW=r.height/s.startWidth;if(s.handle!=='width')this.store.setLength(this.snap(s.startLength+(e.clientX-s.startX)/Math.max(pxL,.0001)));if(s.handle!=='length')this.store.setWidth(this.snap(s.startWidth+(e.clientY-s.startY)/Math.max(pxW,.0001)));}stopResize(){this.dragResizeState=null;}
 addLayer(p:'top'|'bottom'){this.store.addLayer(p);this.syncLinkedElevation();}removeLayer(id:number){this.store.removeLayer(id);this.syncLinkedElevation();}updateLayerMaterial(id:number,materialId:string|null){if(materialId){this.store.setLayerMaterial(id,materialId);this.syncLinkedElevation();}}updateLayerColor(id:number,e:Event){this.store.updateLayer(id,{color:(e.target as HTMLInputElement).value});}updateLayerThickness(id:number,e:Event){const l=this.layers().find(x=>x.id===id);if(l){this.store.updateLayer(id,{thicknessMm:this.read(e,l.thicknessMm,1,2000)});this.syncLinkedElevation();}}updateLayerWallPlacement(id:number,e:Event){this.store.updateLayer(id,{wallPlacement:(e.target as HTMLSelectElement).value as FloorLayerWallPlacement});this.syncLinkedElevation();}
 isLayerVisible(id:number){return!this.hiddenLayerIds().includes(id);}setLayerVisible(id:number,e:Event){this.preferences.setLayerVisible(id,(e.target as HTMLInputElement).checked);}showAllLayers(){this.preferences.showAllLayers();}hideAllLayers(){this.preferences.hideAllLayers(this.layers().map(l=>l.id));}onNavigationModeChange(m:'trackpad'|'mouse'){this.preferences.setNavigationMode(m);}onCameraModeChange(m:CameraModePreference){this.preferences.setCameraMode(m);}updateCameraMode(e:Event){this.preferences.setCameraMode((e.target as HTMLSelectElement).value as CameraModePreference);}onCameraChange(c:{position:[number,number,number];target:[number,number,number];zoom:number}){this.preferences.setCamera(c);}
 startLayerDrag(id:number,e:DragEvent){this.draggedLayerId=id;e.dataTransfer?.setData('text/plain',String(id));}allowLayerDrop(id:number,e:DragEvent){e.preventDefault();const b=(e.currentTarget as HTMLElement).getBoundingClientRect();this.dragOverLayerId.set(id);this.dragOverPosition.set(e.clientY<b.top+b.height/2?'before':'after');}dropLayer(id:number,e:DragEvent){e.preventDefault();const src=this.draggedLayerId??Number(e.dataTransfer?.getData('text/plain')),pos=this.dragOverPosition()??'before';this.endLayerDrag();if(src!==id){this.store.reorderLayers(src,id,pos);this.syncLinkedElevation();}}endLayerDrag(){this.draggedLayerId=null;this.dragOverLayerId.set(null);this.dragOverPosition.set(null);}
 private syncLinkedElevation(){const storey=this.linkedStorey();if(storey)this.store.setElevation(storey.baseElevationMm+this.underWallsThicknessMm());}
 private snap(v:number){const step=this.gridStepMm(),n=this.snapToGrid()?Math.round(v/step)*step:Math.round(v);return Math.min(50000,Math.max(500,n));}private read(e:Event,f:number,min:number,max:number){const v=Number((e.target as HTMLInputElement).value);return Number.isFinite(v)?Math.min(max,Math.max(min,Math.round(v))):f;}
}
