import { AfterViewInit, ChangeDetectionStrategy, Component, ElementRef, EventEmitter, Input, OnChanges, OnDestroy, Output, SimpleChanges, ViewChild, signal } from '@angular/core';
import { ThreeDEngine, floorFieldToObject3D } from '@smartbarn/3d-engine';
import type { FloorFieldModel } from '@smartbarn/domain';
import * as THREE from 'three';

type NavigationMode = 'trackpad' | 'mouse';
interface FloorLayer3d { readonly id:number; readonly kind:string; readonly name:string; readonly thicknessMm:number; readonly color?:string; }
export interface CameraState { readonly position:[number,number,number]; readonly target:[number,number,number]; readonly zoom:number; }

@Component({selector:'smartbarn-floor-field-3d',standalone:true,changeDetection:ChangeDetectionStrategy.OnPush,template:`<div class="viewport-shell"><div class="viewport-toolbar"><button type="button" [class.active]="navigationMode()==='trackpad'" (click)="setNavigationMode('trackpad')">Trackpad</button><button type="button" [class.active]="navigationMode()==='mouse'" (click)="setNavigationMode('mouse')">Mouse</button><button type="button" (click)="fitView()">Center</button><button type="button" (click)="resetView()">Top</button></div><div #viewport class="viewport"></div><div class="viewport-hint">{{navigationMode()==='trackpad'?'1 finger move · 2 fingers orbit · pinch zoom':'Middle drag orbit · Shift + Middle pan · Wheel zoom'}}</div></div>`,styles:`:host{display:block;width:100%;height:100%;min-height:0}.viewport-shell{position:relative;width:100%;height:100%;min-height:0;overflow:hidden;border-radius:var(--sb-radius-3);background:radial-gradient(circle at 50% 45%,var(--sb-accent-soft),transparent 42%),var(--sb-surface)}.viewport{width:100%;height:100%;min-height:0}.viewport-toolbar{position:absolute;z-index:3;top:.75rem;left:50%;transform:translateX(-50%);display:flex;gap:.35rem;padding:.3rem;border:1px solid var(--sb-border);border-radius:999px;background:color-mix(in srgb,var(--sb-surface-raised) 92%,transparent)}.viewport-toolbar button{border:0;border-radius:999px;padding:.42rem .72rem;background:transparent;color:var(--sb-text-muted);cursor:pointer}.viewport-toolbar button.active{background:var(--sb-accent-soft);color:var(--sb-text)}.viewport-hint{position:absolute;right:.75rem;bottom:.75rem;padding:.4rem .55rem;color:var(--sb-text-muted);font-size:.72rem}`})
export class FloorField3dComponent implements AfterViewInit,OnChanges,OnDestroy{
 @Input({required:true}) lengthMm=9000;@Input({required:true}) widthMm=6000;@Input({required:true}) elevationMm=0;@Input({required:true}) layers:readonly FloorLayer3d[]=[];@Input() showGrid=false;@Input() initialNavigationMode:NavigationMode='trackpad';@Input() initialCamera:CameraState|null=null;@Input() hiddenLayerIds:readonly number[]=[];
 @Output() readonly navigationModeChange=new EventEmitter<NavigationMode>();@Output() readonly cameraChange=new EventEmitter<CameraState>();
 @ViewChild('viewport',{static:true}) private readonly viewport?:ElementRef<HTMLDivElement>;readonly navigationMode=signal<NavigationMode>('trackpad');
 private engine?:ThreeDEngine;private floorObject?:THREE.Object3D;private grid?:THREE.GridHelper;private frameId?:number;private resizeObserver?:ResizeObserver;private hasInitialView=false;private readonly raycaster=new THREE.Raycaster();private trackpadOrbitActiveUntil=0;
 ngAfterViewInit(){const container=this.viewport?.nativeElement;if(!container)return;this.navigationMode.set(this.initialNavigationMode);this.engine=new ThreeDEngine({container,antialias:true});this.engine.renderer.setClearColor(0x000000,0);Object.assign(this.engine.controls,{minDistance:.5,maxDistance:200,enableDamping:true,dampingFactor:.09,rotateSpeed:.75,panSpeed:.9,zoomSpeed:1.15,screenSpacePanning:true,zoomToCursor:true});this.grid=new THREE.GridHelper(30,30,0x64748b,0x94a3b8);this.grid.position.y=-.002;this.grid.material.transparent=true;this.grid.material.opacity=.28;this.grid.visible=this.showGrid;this.engine.scene.add(this.grid);this.resizeObserver=new ResizeObserver(()=>this.engine?.resize());this.resizeObserver.observe(container);const canvas=this.engine.renderer.domElement;canvas.addEventListener('wheel',this.handleTrackpadWheel,{capture:true,passive:false});canvas.addEventListener('pointerdown',this.handleMousePointerDown,{capture:true});canvas.addEventListener('contextmenu',this.preventContextMenu);this.engine.controls.addEventListener('change',this.handleControlsChange);this.applyNavigationMode();this.rebuildScene();this.animate();}
 ngOnChanges(changes:SimpleChanges){if(this.grid&&changes['showGrid'])this.grid.visible=this.showGrid;if(this.engine&&(changes['lengthMm']||changes['widthMm']||changes['elevationMm']||changes['layers']))this.rebuildScene();else if(this.floorObject&&changes['hiddenLayerIds'])this.applyLayerVisibility();if(this.engine&&changes['initialNavigationMode']){this.navigationMode.set(this.initialNavigationMode);this.applyNavigationMode();}}
 ngOnDestroy(){if(this.frameId!==undefined)cancelAnimationFrame(this.frameId);this.resizeObserver?.disconnect();if(this.engine){const c=this.engine.renderer.domElement;c.removeEventListener('wheel',this.handleTrackpadWheel,true);c.removeEventListener('pointerdown',this.handleMousePointerDown,true);c.removeEventListener('contextmenu',this.preventContextMenu);this.engine.controls.removeEventListener('change',this.handleControlsChange);}this.disposeFloorObject();this.engine?.dispose();}
 setNavigationMode(mode:NavigationMode){this.navigationMode.set(mode);this.applyNavigationMode();this.navigationModeChange.emit(mode);}
 fitView(){this.fit(false);} resetView(){this.fit(true);}
 private fit(top:boolean){if(!this.engine||!this.floorObject)return;this.engine.resize();const box=new THREE.Box3().setFromObject(this.floorObject);if(box.isEmpty())return;const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),camera=this.engine.camera,controls=this.engine.controls;camera.zoom=1;camera.updateProjectionMatrix();const direction=top?new THREE.Vector3(0,1,.0001).normalize():new THREE.Vector3(1,.72,1).normalize(),up=top?new THREE.Vector3(0,0,-1):camera.up.clone().normalize(),right=new THREE.Vector3().crossVectors(direction,up).normalize(),viewUp=new THREE.Vector3().crossVectors(right,direction).normalize();let hw=0,hh=0;for(const x of [-size.x/2,size.x/2])for(const y of [-size.y/2,size.y/2])for(const z of [-size.z/2,size.z/2]){const p=new THREE.Vector3(x,y,z);hw=Math.max(hw,Math.abs(p.dot(right)));hh=Math.max(hh,Math.abs(p.dot(viewUp)));}const vf=THREE.MathUtils.degToRad(camera.fov),hf=2*Math.atan(Math.tan(vf/2)*Math.max(camera.aspect,.001)),distance=Math.max(4,hw/Math.tan(hf/2),hh/Math.tan(vf/2))*1.18;camera.up.copy(up);camera.position.copy(center).addScaledVector(direction,distance);camera.near=Math.max(.01,distance/1000);camera.far=Math.max(1000,distance*100);camera.updateProjectionMatrix();controls.target.copy(center);camera.lookAt(center);controls.update();this.hasInitialView=true;this.emitCamera();this.engine.render();}
 private applyNavigationMode(){if(!this.engine)return;const c=this.engine.controls;if(this.navigationMode()==='trackpad'){c.mouseButtons.LEFT=THREE.MOUSE.PAN;c.mouseButtons.MIDDLE=THREE.MOUSE.ROTATE;c.mouseButtons.RIGHT=THREE.MOUSE.PAN;c.touches.ONE=THREE.TOUCH.PAN;c.touches.TWO=THREE.TOUCH.DOLLY_ROTATE;}else{c.mouseButtons.LEFT=THREE.MOUSE.ROTATE;c.mouseButtons.MIDDLE=THREE.MOUSE.ROTATE;c.mouseButtons.RIGHT=THREE.MOUSE.PAN;c.touches.ONE=THREE.TOUCH.ROTATE;c.touches.TWO=THREE.TOUCH.DOLLY_PAN;}}
 private readonly handleMousePointerDown=(e:PointerEvent)=>{if(!this.engine||this.navigationMode()!=='mouse'||e.pointerType!=='mouse')return;if(e.button===1)this.engine.controls.mouseButtons.MIDDLE=e.shiftKey?THREE.MOUSE.PAN:THREE.MOUSE.ROTATE;if(e.button===0||(e.button===1&&!e.shiftKey))this.setOrbitPivot(e.clientX,e.clientY);};private readonly preventContextMenu=(e:MouseEvent)=>e.preventDefault();private readonly handleControlsChange=()=>this.emitCamera();
 private readonly handleTrackpadWheel=(e:WheelEvent)=>{if(!this.engine||this.navigationMode()!=='trackpad'||e.ctrlKey)return;e.preventDefault();e.stopImmediatePropagation();const now=performance.now();if(now>this.trackpadOrbitActiveUntil)this.setOrbitPivot(e.clientX,e.clientY);this.trackpadOrbitActiveUntil=now+180;const camera=this.engine.camera,c=this.engine.controls,offset=camera.position.clone().sub(c.target),s=new THREE.Spherical().setFromVector3(offset);s.theta-=e.deltaX*.0032;s.phi=THREE.MathUtils.clamp(s.phi-e.deltaY*.0032,.08,Math.PI-.08);offset.setFromSpherical(s);camera.position.copy(c.target).add(offset);camera.lookAt(c.target);c.update();this.emitCamera();};
 private setOrbitPivot(x:number,y:number){if(!this.engine||!this.floorObject)return;const rect=this.engine.renderer.domElement.getBoundingClientRect();if(rect.width<=0||rect.height<=0)return;this.raycaster.setFromCamera(new THREE.Vector2(((x-rect.left)/rect.width)*2-1,-((y-rect.top)/rect.height)*2+1),this.engine.camera);const hit=this.raycaster.intersectObject(this.floorObject,true)[0];if(hit)this.engine.controls.target.copy(hit.point);}
 private rebuildScene(){if(!this.engine)return;this.disposeFloorObject();const model:FloorFieldModel={id:'floor-field-preview',entity:'floor-field',geometry:{lengthMm:this.lengthMm,widthMm:this.widthMm,elevationMm:this.elevationMm},layers:this.layers.map((l,i)=>({id:String(l.id),name:l.name,type:l.kind,thicknessMm:l.thicknessMm,color:l.color??this.layerColor(l.kind,i)}))};this.floorObject=floorFieldToObject3D(model);this.floorObject.position.y=this.elevationMm*.001;this.applyLayerVisibility();this.engine.root.add(this.floorObject);if(!this.hasInitialView){if(this.initialCamera)this.restore(this.initialCamera);else this.resetView();this.hasInitialView=true;}}
 private applyLayerVisibility(){if(!this.floorObject)return;const hidden=new Set(this.hiddenLayerIds.map(String));this.floorObject.traverse(object=>{const id=object.userData['smartBarnLayerId'];if(typeof id==='string')object.visible=!hidden.has(id);});}
 private restore(s:CameraState){if(!this.engine)return;this.engine.camera.position.fromArray(s.position);this.engine.camera.zoom=s.zoom;this.engine.camera.updateProjectionMatrix();this.engine.controls.target.fromArray(s.target);this.engine.camera.lookAt(this.engine.controls.target);this.engine.controls.update();}
 private emitCamera(){if(!this.engine)return;this.cameraChange.emit({position:this.engine.camera.position.toArray() as [number,number,number],target:this.engine.controls.target.toArray() as [number,number,number],zoom:this.engine.camera.zoom});}
 private animate=()=>{this.engine?.render();this.frameId=requestAnimationFrame(this.animate);};private disposeFloorObject(){if(!this.floorObject||!this.engine)return;this.engine.root.remove(this.floorObject);this.floorObject.traverse(o=>{if(!(o instanceof THREE.Mesh))return;o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());});this.floorObject=undefined;}private layerColor(k:string,i:number){const c:Record<string,string>={sip:'#d9b36c',finish:'#c58d5b',screed:'#a8a29e',insulation:'#eab308',structure:'#64748b',ceiling:'#e2e8f0',custom:'#38bdf8'};return c[k]??['#38bdf8','#a78bfa','#34d399'][i%3];}
}
