import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';
import { FloorField3dComponent } from './floor-field-3d.component';

type FloorFieldView = 'geometry' | 'layers' | '3d';
type ResizeHandle = 'length' | 'width' | 'both';
interface PreviewRect { readonly x:number; readonly y:number; readonly width:number; readonly height:number; }
interface FloorLayer { readonly id:number; readonly kind:string; readonly name:string; readonly thicknessMm:number; readonly color:string; }

@Component({selector:'smartbarn-floor-field-page',standalone:true,imports:[FloorField3dComponent],changeDetection:ChangeDetectionStrategy.OnPush,templateUrl:'./floor-field.page.html',styleUrl:'./floor-field.page.scss'})
export class FloorFieldPage {
 private static readonly MIN=500; private static readonly MAX=50000; private nextLayerId=4; private draggedLayerId:number|null=null; private dragResizeState:{handle:ResizeHandle;startX:number;startY:number;startLength:number;startWidth:number}|null=null;
 readonly lengthMm=signal(9000); readonly widthMm=signal(6000); readonly elevationMm=signal(0); readonly gridStepMm=signal(100); readonly snapToGrid=signal(true); readonly activeView=signal<FloorFieldView>('geometry'); readonly inspectorOpen=signal(true);
 readonly layers=signal<readonly FloorLayer[]>([{id:1,kind:'osb',name:'OSB верхний',thicknessMm:12,color:'#f5d77a'},{id:2,kind:'structure',name:'Балки + теплоизоляция',thicknessMm:200,color:'#e58b2a'},{id:3,kind:'osb',name:'OSB нижний',thicknessMm:12,color:'#f5d77a'}]);
 readonly dragOverLayerId=signal<number|null>(null); readonly dragOverPosition=signal<'before'|'after'|null>(null);
 readonly totalLayerThicknessMm=computed(()=>this.layers().reduce((s,l)=>s+l.thicknessMm,0));
 readonly previewRect=computed<PreviewRect>(()=>{const aw=760,ah=500,a=this.lengthMm()/this.widthMm(),aa=aw/ah,w=a>=aa?aw:ah*a,h=a>=aa?aw/a:ah;return{x:(1000-w)/2,y:(650-h)/2,width:w,height:h};});
 setActiveView(v:FloorFieldView){this.activeView.set(v);} toggleInspector(){this.inspectorOpen.update(v=>!v);} toggleSnapToGrid(){this.snapToGrid.update(v=>!v);}
 updateLength(e:Event){this.lengthMm.set(this.snap(this.read(e,this.lengthMm(),FloorFieldPage.MIN,FloorFieldPage.MAX)));} updateWidth(e:Event){this.widthMm.set(this.snap(this.read(e,this.widthMm(),FloorFieldPage.MIN,FloorFieldPage.MAX)));} updateElevation(e:Event){this.elevationMm.set(this.read(e,this.elevationMm(),-10000,50000));} updateGridStep(e:Event){this.gridStepMm.set(this.read(e,this.gridStepMm(),10,5000));}
 swapDimensions(){const l=this.lengthMm();this.lengthMm.set(this.widthMm());this.widthMm.set(l);} resetGeometry(){this.lengthMm.set(9000);this.widthMm.set(6000);this.elevationMm.set(0);this.gridStepMm.set(100);this.snapToGrid.set(true);}
 startResize(handle:ResizeHandle,e:PointerEvent){e.preventDefault();(e.currentTarget as Element).setPointerCapture?.(e.pointerId);this.dragResizeState={handle,startX:e.clientX,startY:e.clientY,startLength:this.lengthMm(),startWidth:this.widthMm()};}
 resizeGeometry(e:PointerEvent){const s=this.dragResizeState;if(!s)return;const r=this.previewRect(),pxL=r.width/s.startLength,pxW=r.height/s.startWidth;if(s.handle!=='width')this.lengthMm.set(this.snap(s.startLength+(e.clientX-s.startX)/Math.max(pxL,.0001)));if(s.handle!=='length')this.widthMm.set(this.snap(s.startWidth+(e.clientY-s.startY)/Math.max(pxW,.0001)));} stopResize(){this.dragResizeState=null;}
 addLayer(position:'top'|'bottom'){const layer:FloorLayer={id:this.nextLayerId++,kind:'custom',name:'Новый слой',thicknessMm:20,color:'#8ab4f8'};this.layers.update(ls=>position==='top'?[layer,...ls]:[...ls,layer]);} removeLayer(id:number){this.layers.update(ls=>ls.filter(l=>l.id!==id));}
 updateLayerName(id:number,e:Event){const name=(e.target as HTMLInputElement).value||'Слой';this.layers.update(ls=>ls.map(l=>l.id===id?{...l,name}:l));} updateLayerColor(id:number,e:Event){const color=(e.target as HTMLInputElement).value;this.layers.update(ls=>ls.map(l=>l.id===id?{...l,color}:l));} updateLayerThickness(id:number,e:Event){this.layers.update(ls=>ls.map(l=>l.id===id?{...l,thicknessMm:this.read(e,l.thicknessMm,1,2000)}:l));}
 startLayerDrag(id:number,e:DragEvent){this.draggedLayerId=id;e.dataTransfer?.setData('text/plain',String(id));} allowLayerDrop(id:number,e:DragEvent){e.preventDefault();const b=(e.currentTarget as HTMLElement).getBoundingClientRect();this.dragOverLayerId.set(id);this.dragOverPosition.set(e.clientY<b.top+b.height/2?'before':'after');} dropLayer(id:number,e:DragEvent){e.preventDefault();const src=this.draggedLayerId??Number(e.dataTransfer?.getData('text/plain')),pos=this.dragOverPosition()??'before';this.endLayerDrag();if(src===id)return;this.layers.update(ls=>{const a=[...ls],si=a.findIndex(l=>l.id===src);let ti=a.findIndex(l=>l.id===id);if(si<0||ti<0)return ls;const[m]=a.splice(si,1);if(si<ti)ti--;a.splice(pos==='after'?ti+1:ti,0,m);return a;});} endLayerDrag(){this.draggedLayerId=null;this.dragOverLayerId.set(null);this.dragOverPosition.set(null);}
 private snap(v:number){const step=this.gridStepMm();const n=this.snapToGrid()?Math.round(v/step)*step:Math.round(v);return Math.min(FloorFieldPage.MAX,Math.max(FloorFieldPage.MIN,n));} private read(e:Event,f:number,min:number,max:number){const v=Number((e.target as HTMLInputElement).value);return Number.isFinite(v)?Math.min(max,Math.max(min,Math.round(v))):f;}
}
