import { AfterViewInit, ChangeDetectionStrategy, Component, ElementRef, Input, OnChanges, OnDestroy, SimpleChanges, ViewChild, signal } from '@angular/core';
import { ThreeDEngine, floorFieldToObject3D } from '@smartbarn/3d-engine';
import type { FloorFieldModel } from '@smartbarn/domain';
import * as THREE from 'three';

type NavigationMode = 'trackpad' | 'mouse';
interface FloorLayer3d { readonly id: number; readonly kind: string; readonly name: string; readonly thicknessMm: number; readonly color?: string; }

@Component({
  selector: 'smartbarn-floor-field-3d', standalone: true, changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<div class="viewport-shell"><div class="viewport-toolbar"><button type="button" [class.active]="navigationMode() === 'trackpad'" (click)="setNavigationMode('trackpad')">Trackpad</button><button type="button" [class.active]="navigationMode() === 'mouse'" (click)="setNavigationMode('mouse')">Mouse</button><button type="button" (click)="fitView()">Center</button></div><div #viewport class="viewport"></div><div class="viewport-hint">{{ navigationMode() === 'trackpad' ? '1 finger rotate · 2 fingers pan · pinch zoom' : 'Left rotate · Right pan · Wheel zoom' }}</div></div>`,
  styles: `:host{display:block}.viewport-shell{position:relative;min-height:30rem;overflow:hidden;border-radius:var(--sb-radius-3);background:radial-gradient(circle at 50% 45%,var(--sb-accent-soft),transparent 42%),var(--sb-surface)}.viewport{width:100%;height:clamp(30rem,68vh,54rem)}.viewport-toolbar{position:absolute;z-index:3;top:.75rem;left:50%;transform:translateX(-50%);display:flex;gap:.35rem;padding:.3rem;border:1px solid var(--sb-border);border-radius:999px;background:color-mix(in srgb,var(--sb-surface-raised) 92%,transparent);backdrop-filter:blur(8px)}.viewport-toolbar button{border:0;border-radius:999px;padding:.42rem .72rem;background:transparent;color:var(--sb-text-muted);cursor:pointer}.viewport-toolbar button.active{background:var(--sb-accent-soft);color:var(--sb-text)}.viewport-hint{position:absolute;right:.75rem;bottom:.75rem;border:1px solid var(--sb-border);border-radius:var(--sb-radius-2);background:color-mix(in srgb,var(--sb-surface-raised) 88%,transparent);padding:.4rem .55rem;color:var(--sb-text-muted);font-size:.72rem;pointer-events:none;backdrop-filter:blur(8px)}`,
})
export class FloorField3dComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input({ required: true }) lengthMm = 9_000; @Input({ required: true }) widthMm = 6_000; @Input({ required: true }) elevationMm = 0; @Input({ required: true }) layers: readonly FloorLayer3d[] = [];
  @ViewChild('viewport', { static: true }) private readonly viewport?: ElementRef<HTMLDivElement>;
  readonly navigationMode = signal<NavigationMode>('trackpad');
  private engine?: ThreeDEngine; private floorObject?: THREE.Object3D; private frameId?: number; private resizeObserver?: ResizeObserver;
  ngAfterViewInit(): void { const container=this.viewport?.nativeElement;if(!container)return;this.engine=new ThreeDEngine({container,antialias:true});this.engine.renderer.setClearColor(0x000000,0);this.engine.controls.minDistance=2;this.engine.controls.maxDistance=80;const grid=new THREE.GridHelper(30,30,0x64748b,0x94a3b8);grid.position.y=-.002;grid.material.transparent=true;grid.material.opacity=.28;this.engine.scene.add(grid);this.resizeObserver=new ResizeObserver(()=>{this.engine?.resize();this.fitView();});this.resizeObserver.observe(container);this.applyNavigationMode();this.rebuildScene();this.animate(); }
  ngOnChanges(_changes:SimpleChanges):void{if(this.engine)this.rebuildScene();}
  ngOnDestroy():void{if(this.frameId!==undefined)cancelAnimationFrame(this.frameId);this.resizeObserver?.disconnect();this.disposeFloorObject();this.engine?.dispose();}
  setNavigationMode(mode:NavigationMode):void{this.navigationMode.set(mode);this.applyNavigationMode();}
  fitView():void{if(!this.engine)return;const size=Math.max(this.lengthMm,this.widthMm)*.001;const distance=Math.max(7,size*1.15);this.engine.camera.position.set(distance,distance*.72,distance);this.engine.controls.target.set(0,-this.totalThicknessMeters()/2,0);this.engine.camera.lookAt(this.engine.controls.target);this.engine.controls.update();}
  private applyNavigationMode():void{if(!this.engine)return;const c=this.engine.controls;c.enableDamping=true;c.dampingFactor=.08;c.screenSpacePanning=true;if(this.navigationMode()==='trackpad'){c.mouseButtons.LEFT=THREE.MOUSE.ROTATE;c.mouseButtons.MIDDLE=THREE.MOUSE.DOLLY;c.mouseButtons.RIGHT=THREE.MOUSE.PAN;c.touches.ONE=THREE.TOUCH.ROTATE;c.touches.TWO=THREE.TOUCH.DOLLY_PAN;}else{c.mouseButtons.LEFT=THREE.MOUSE.ROTATE;c.mouseButtons.MIDDLE=THREE.MOUSE.DOLLY;c.mouseButtons.RIGHT=THREE.MOUSE.PAN;c.touches.ONE=THREE.TOUCH.ROTATE;c.touches.TWO=THREE.TOUCH.DOLLY_PAN;}}
  private rebuildScene():void{if(!this.engine)return;this.disposeFloorObject();const model:FloorFieldModel={id:'floor-field-preview',entity:'floor-field',geometry:{lengthMm:this.lengthMm,widthMm:this.widthMm,elevationMm:this.elevationMm},layers:this.layers.map((layer,index)=>({id:String(layer.id),name:layer.name,type:layer.kind,thicknessMm:layer.thicknessMm,color:layer.color??this.layerColor(layer.kind,index)}))};this.floorObject=floorFieldToObject3D(model);this.floorObject.position.y=this.elevationMm*.001;this.engine.root.add(this.floorObject);this.fitView();}
  private animate=():void=>{this.engine?.render();this.frameId=requestAnimationFrame(this.animate);};
  private disposeFloorObject():void{if(!this.floorObject||!this.engine)return;this.engine.root.remove(this.floorObject);this.floorObject.traverse((object)=>{if(!(object instanceof THREE.Mesh))return;object.geometry.dispose();const materials=Array.isArray(object.material)?object.material:[object.material];materials.forEach((material)=>material.dispose());});this.floorObject=undefined;}
  private totalThicknessMeters():number{return this.layers.reduce((sum,layer)=>sum+layer.thicknessMm,0)*.001;}
  private layerColor(kind:string,index:number):string{const colors:Record<string,string>={sip:'#d9b36c',finish:'#c58d5b',screed:'#a8a29e',insulation:'#eab308',structure:'#64748b',ceiling:'#e2e8f0',custom:'#38bdf8'};return colors[kind]??['#38bdf8','#a78bfa','#34d399'][index%3];}
}
