import { ChangeDetectionStrategy, Component, computed, input, model, output, signal } from '@angular/core';
import type { FormValueControl } from '@angular/forms/signals';

export interface SearchComboboxItem {
  readonly value: string;
  readonly label: string;
  readonly searchText?: string;
  readonly disabled?: boolean;
}

export interface SearchComboboxGroup {
  readonly id: string;
  readonly label: string;
  readonly items: readonly SearchComboboxItem[];
}

/**
 * SmartBarn UI-kit searchable single-value combobox.
 *
 * Public API is intentionally signal-first and compatible with Angular 22
 * Signal Forms through FormValueControl. Domain-specific wrappers should map
 * their entities to SearchComboboxGroup instead of adding domain knowledge here.
 *
 * The component mirrors the Spartan combobox interaction model (search input,
 * grouped options, non-selectable group labels, single selected value). Keeping
 * the API in the UI kit lets the internal primitive be replaced/generated by
 * Spartan without changing application-level components.
 */
@Component({
  selector: 'sb-search-combobox',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'block min-w-0' },
  template: `
    <div class="relative" (focusout)="onFocusOut($event)">
      <button
        type="button"
        class="flex min-h-9 w-full items-center gap-2 rounded border border-[var(--sb-border)] bg-[var(--sb-surface)] px-3 py-2 text-left text-sm outline-none focus:border-[var(--sb-accent)]"
        [disabled]="disabled()"
        [attr.aria-expanded]="open()"
        aria-haspopup="listbox"
        (click)="toggle()"
      >
        <span class="min-w-0 flex-1 truncate" [class.text-[var(--sb-text-muted)]]="!selectedLabel()">{{ selectedLabel() || placeholder() }}</span>
        <span class="shrink-0 text-xs text-[var(--sb-text-muted)]">⌄</span>
      </button>

      @if (open()) {
        <div class="absolute left-0 top-[calc(100%+4px)] z-50 w-full min-w-[260px] rounded-md border border-[var(--sb-border)] bg-[var(--sb-surface)] p-1 shadow-xl">
          <input
            #searchInput
            type="search"
            class="mb-1 w-full rounded border border-[var(--sb-border)] bg-[var(--sb-bg)] px-3 py-2 text-sm outline-none focus:border-[var(--sb-accent)]"
            [value]="query()"
            [placeholder]="searchPlaceholder()"
            (input)="setQuery($event)"
            (keydown.escape)="close()"
          />
          <div class="max-h-72 overflow-auto" role="listbox">
            @for (group of filteredGroups(); track group.id) {
              <div class="px-2 pb-1 pt-2 text-[11px] font-semibold uppercase tracking-wide text-[var(--sb-text-muted)]" role="presentation">{{ group.label }}</div>
              @for (item of group.items; track item.value) {
                <button
                  type="button"
                  role="option"
                  class="flex w-full items-center rounded px-2 py-2 text-left text-sm hover:bg-[var(--sb-accent-soft)] disabled:opacity-50"
                  [disabled]="item.disabled"
                  [attr.aria-selected]="value()===item.value"
                  (click)="select(item.value)"
                >
                  <span class="min-w-0 flex-1 truncate">{{ item.label }}</span>
                  @if (value() === item.value) { <span class="ml-2">✓</span> }
                </button>
              }
            }
            @if (!filteredGroups().length) {
              <div class="px-3 py-6 text-center text-sm text-[var(--sb-text-muted)]">{{ emptyText() }}</div>
            }
          </div>
        </div>
      }
    </div>
  `,
})
export class SearchComboboxComponent implements FormValueControl<string | null> {
  readonly value = model<string | null>(null);
  readonly groups = input.required<readonly SearchComboboxGroup[]>();
  readonly placeholder = input('Выберите значение');
  readonly searchPlaceholder = input('Поиск…');
  readonly emptyText = input('Ничего не найдено');
  readonly disabled = input(false);
  readonly touch = output<void>();

  readonly open = signal(false);
  readonly query = signal('');

  readonly selectedLabel = computed(() => {
    const selected = this.value();
    if (!selected) return '';
    for (const group of this.groups()) {
      const item = group.items.find((candidate) => candidate.value === selected);
      if (item) return item.label;
    }
    return '';
  });

  readonly filteredGroups = computed<readonly SearchComboboxGroup[]>(() => {
    const query = this.normalize(this.query());
    if (!query) return this.groups().filter((group) => group.items.length > 0);
    return this.groups()
      .map((group) => ({
        ...group,
        items: group.items.filter((item) =>
          this.normalize(`${group.label} ${item.label} ${item.searchText ?? ''}`).includes(query),
        ),
      }))
      .filter((group) => group.items.length > 0);
  });

  toggle(): void {
    if (this.disabled()) return;
    this.open.update((value) => !value);
    if (!this.open()) this.touch.emit();
  }

  close(): void {
    if (!this.open()) return;
    this.open.set(false);
    this.query.set('');
    this.touch.emit();
  }

  select(value: string): void {
    this.value.set(value);
    this.close();
  }

  setQuery(event: Event): void {
    this.query.set((event.target as HTMLInputElement).value);
  }

  onFocusOut(event: FocusEvent): void {
    const host = event.currentTarget as HTMLElement;
    const next = event.relatedTarget as Node | null;
    if (next && host.contains(next)) return;
    this.close();
  }

  focus(): void {
    this.open.set(true);
  }

  reset(): void {
    this.value.set(null);
    this.query.set('');
    this.open.set(false);
  }

  private normalize(value: string): string {
    return value.trim().toLocaleLowerCase();
  }
}
